### ISSUE TITLE
Unable to join 1.12.2 server on a 1.13 client through BungeeCord with ViaVersion.

### ISSUE THREAD

**Issue by mibby** [MylesIsCool/ViaVersion#981]
**Bungee Environment**
Waterfall dev 218
https://destroystokyo.com/ci/view/all/job/Waterfall/
ViaVersion dev 224
https://ci.viaversion.com/view/All/job/ViaVersion/

**Server Environment**
Paper dev 1547 _(Spigot 1.12.2)_
https://destroystokyo.com/ci/view/all/job/Paper/
ProtocolSupport dev 242 _(Last Spigot 1.12.2 supported build)_
https://build.true-games.org/job/ProtocolSupport

When I try connecting through BungeeCord to a 1.12.2 Spigot server with a 1.13 client, I get disconnected from the server with Spigot's ```outdated-server``` message.

I have also tried ViaVersion-DEV dev 154 on BungeeCord but unfortunately run into the same issue.

Is ViaVersion not compatible with ProtocolSupport? I know the main Spigot page says to use ViaVersion on BungeeCord as a workaround, but it doesn't seem to let me connect with a higher client version doing so. ViaBackwards is missing some features like remapping maps to older versions so I use ProtocolSupport for server client support <1.12.

**Comment by MylesIsCool** [comment]
You have to manually set the protocol versions to work around this via the ViaVersion config (and disable auto-updating).

It's not compatible when they're on Spigot togehter in 1.12, in the future please provide dumps as they can be vital to finding the issue.

**Comment by mibby** [comment]
How would I manually set the protocol versions? I already have auto-update disabled.

```
# Should ViaVersion check for updates?
checkforupdates: false
```

```
bungee-servers:
  default: 47
  Server: -1
```

**Comment by mibby** [comment]
@MylesIsCool Do you mean forcing the server protocol higher than what the server version actually is?

i.e
```
# 
# ----------------------------------------------------------#
#                     BUNGEE OPTIONS                       #
# ----------------------------------------------------------#
# 
# BungeeCord allows you to have different server versions inside.
# Instead of you entering all the versions of these servers, we can ping them.
# 
# What interval would you like us to ping at? (in seconds)
# Use -1 to disable.
bungee-ping-interval: 60
# If the above is enabled, should we save the info to the config (in the section below)
bungee-ping-save: false
# To get a servers protocol, ViaVersion will do the following:
# Look for the server in the following section, then look for the last ping if bungee-ping is enabled
# otherwise use default.
# 
# The format for the following is:
#  servername: protocolversion
# You can find protocol ids on http://wiki.vg/Protocol_version_numbers
# It will fallback to the default option if none found.
bungee-servers:
  default: 47
  Server: 399
```
